import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Sale from '@/components/sale/sale'
import Pool from '@/components/pool/pool'
import Women from '@/components/women/women'
import Members from '@/components/members/members'
import Pants from '@/components/pants/pants'
import Nature from '@/components/nature/nature'
import Magazine from '@/components/magazine/magazine'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
           <Sale/>
           <Pool/>
           <Women/>
           <Members/>
           <Pants/>
           <Nature/>
           <Magazine/>
      </main>
    </>
  )
}
