import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Sale from '@/components/sale/sale'
import Pool from '@/components/pool/pool'
import Women from '@/components/women/women'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
           <Sale/>
           <Pool/>
           <Women/>
      </main>
    </>
  )
}
